### ISSUE TITLE
Constant data-spacing

### ISSUE THREAD

**Issue by neheller** [neheller/kits19#1]
React with a :thumbsup: if you would find useful a separate branch(es) with the data and labels transformed to fixed `pixel_width` and `slice_thickness`.

**Comment by neheller** [comment]
This is in progress and will be part of the April 15 release. Our plan is to interpolate to the overall medians of slice thickness and pixel width. That will be a slice thickness of 3.0 mm and a pixel width of 0.781625 mm. 

The testing set release will also include a copy of the data transformed to this spacing. For evaluation, participants will be allowed to submit predictions either in original spacing or in median spacing.

**Comment by neheller** [comment]
Unfortunately we're going to have to push this back to April 22 to finish ironing out the kinks with the interpolation method. Since we will be evaluating teams based on these labels, we want to make sure we hold them to the same standard as the labels in original spacing, and right now a handful of cases are exhibiting some pesky artifacts. Thanks for your patience while we work through them.

The amended labels in original spacing will be released today as planned.

**Comment by neheller** [comment]
The data at constant spacing has been pushed to a new branch called `interpolated`. If you've already cloned the repository, you can use the following commands from the repository root
```
git fetch
git checkout origin/interpolated
```
If you have not yet cloned the repository and you would only like to download only the interpolated data, you can use
```
git clone -b interpolated --single-branch https://github.com/neheller/kits19
```
On my machine, the interpolated data occupies roughly 50GB. 

Enjoy!

**Comment by JunMa11** [comment]
Hi @neheller ,
Thanks for providing the interpolated data.

I have installed `git-lfs`, but the downloaded data is not complete. Each data only has `1 KB`.

![download error](http://i2.bvimg.com/595387/9e3060c959d597a3.png)

Would it be possible for you to give me some insights on what's wrong with my download?

**Comment by neheller** [comment]
Interesting, I'm not a windows user so I'm not really sure what the problem is here. Can anyone else shed some light? 

When I originally tested the LFS functionality on Windows I used the GitHub GUI and it worked without issue.

**Comment by JunMa11** [comment]
Black magic! 
I try another windows computer, it works! But the first computer still does not work even by github bash.
Anyway, I can access the interpolated data.
Thanks for your quick reply. @neheller
