### ISSUE TITLE
CID 155 cyst mislabeled as background?

### ISSUE THREAD

**Issue by t-suzuki** [neheller/kits19#10]
I found the left kidney of cid=155 has a cyst-like blob labeled as background near the kidney hilum.

![image](https://user-images.githubusercontent.com/4010133/55442534-ebefdf00-5563-11e9-9531-ac8c260bb5dc.png)

Is this not a cyst (which should be labeled 0) or a tumor(1)?
I would also appreciate if organizers share us how annotators tell this from cysts and tumors.

Thanks in advance.

**Comment by neheller** [comment]
Thanks for pointing this out! This is an error on our part. During the annotation process, this parapelvic cyst was mistaken for hydronephrosis. We will fix this in the final training set release on April 15.

**Comment by neheller** [comment]
This has been addressed in the amended release.
