### ISSUE TITLE
Holes in annotations of large kidney tumors

### ISSUE THREAD

**Issue by ghumpire** [neheller/kits19#12]
I think this was not reported before; I noticed that cases 42 and 114 have a lot of holes in the annotations of the kidney tumor. Note that both cases have large kidney tumors, I did not see this problem on small kidney tumors.  See image below of case 42:

![kidney_tumor_holes](https://user-images.githubusercontent.com/190246/55464369-425c2c80-55fb-11e9-8e04-35e734398c52.png)

**Comment by neheller** [comment]
Thanks for catching this! Our annotation procedure made use of a threshold, and it looks like it was set slightly too high for these hypodense tumors. I'll re-check the remainder and make sure this isn't the case in the final training set release.

**Comment by neheller** [comment]
This has been addressed in the amended release. Please feel free to reopen if you still see it.
