### ISSUE TITLE
Dimention (width) of case_00160 is not same 

### ISSUE THREAD

**Issue by sharmarochan** [neheller/kits19#13]
The width of case_00160 is not same as others i.e. (*, 512, 796), thus it may return error while input in Neural network. 

The dimension of all the other cases is (*, 512, 512)

*  *means variable depth of nifti image

**Comment by sharmarochan** [comment]
ValueError: could not broadcast input array from shape (512,512,1) into shape (512)

**Comment by neheller** [comment]
CT scans do not produce constant image sizes in general. I recommend that you incorporate a step in your data pipeline to transform the data to a desired shape, perhaps as part of your data augmentation procedure.
