### ISSUE TITLE
Cannot downloading data

### ISSUE THREAD

**Issue by Nandayang** [neheller/kits19#14]
I have cloned without git lfs install and this comes:
$ git clone https://github.com/neheller/kits19.git  
Cloning into 'kits19'...
remote: Enumerating objects: 679, done.
remote: Counting objects: 100% (679/679), done.
remote: Compressing objects: 100% (655/655), done.
Receiving objects:  74%remote: Total 679 (delta 19), reused 679 (delta 19), pack-reused 0
Receiving objects:  88% (598/679), 60.00 KiB | 57.00 KiB/s
Receiving objects: 100% (679/679), 93.87 KiB | 65.00 KiB/s, done.
Resolving deltas: 100% (19/19), done.
After this , there is no respond and any Filtering content process.

when i cloned with git lfs install, i find that each nii file is only 1kb,

Have you solved this problem? Can anyone share this dataset on google drive or baidu drive?
3ks alot!

**Comment by neheller** [comment]
You might find the discussion in #7 helpful. 

What do you see if you run the following?
```bash
user@host~$ git lfs --version
```
It should look something like this:
```
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)
```

Did you make sure to re-**clone** and not just pull after installing git-lfs?

**Comment by Nandayang** [comment]
@neheller i have checked this before i got this problem~ this is what i get: 
git-lfs/2.7.1 (GitHub; windows amd64; go 1.11.5; git 6b7fb6e3)

**Comment by neheller** [comment]
Admittedly I have only tested the clone on Windows using the GitHub Desktop App, but it did work properly. Are you able to give that a try?

**Comment by SmileJET** [comment]
> I have cloned without git lfs install and this comes:
> $ git clone https://github.com/neheller/kits19.git
> Cloning into 'kits19'...
> remote: Enumerating objects: 679, done.
> remote: Counting objects: 100% (679/679), done.
> remote: Compressing objects: 100% (655/655), done.
> Receiving objects: 74%remote: Total 679 (delta 19), reused 679 (delta 19), pack-reused 0
> Receiving objects: 88% (598/679), 60.00 KiB | 57.00 KiB/s
> Receiving objects: 100% (679/679), 93.87 KiB | 65.00 KiB/s, done.
> Resolving deltas: 100% (19/19), done.
> After this , there is no respond and any Filtering content process.
> 
> when i cloned with git lfs install, i find that each nii file is only 1kb,
> 
> Have you solved this problem? Can anyone share this dataset on google drive or baidu drive?
> 3ks alot!

Maybe you can download the data 'view Raw' one by one.
I have downloaded the data file by Thunder, which is much faster than git on my computer.

**Comment by Nandayang** [comment]
@neheller you know in China there is a GFW and our connection might be unstable.I downloaded it all night last day, while I found the connection was interrupted this morning.I think this situation is very common among Chinese users.  Could you plz put the data set on google drive? Really appreciate

**Comment by SmileJET** [comment]
@Nandayang You can use Thunder to download the data. 
`from win32com.client import Dispatch

o = Dispatch("ThunderAgent.Agent64.1")
for i in range(210):
    url1 = 'https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/imaging.nii.gz'%i
    url2 = 'https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/segmentation.nii.gz'%i
    filename1 = 'imaging_%03d.nii.gz'%i
    filename2 = 'segmentation_%03d.nii.gz'%i
    o.AddTask(url1, filename1)
    o.AddTask(url2, filename2)
o.CommitTasks()`

CSDN BLOG: https://blog.csdn.net/u014657795/article/details/88803504

**Comment by Nandayang** [comment]
@SmileJET Thanks bro!

**Comment by shubham1810** [comment]
You can also download via wget. I wrote a small bash script for the purpose.

`#!/bin/bash

img_url="https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/imaging.nii.gz"
seg_url="https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/segmentation.nii.gz"

j=0
while [ $j -le 210 ]
do
   # echo "$j"
   k=`printf $img_url $j`
   l=`printf $seg_url $j`

   z=`printf "imaging_%05d.nii.gz" $j`
   x=`printf "segmentation_%05d.nii.gz" $j`
   echo "Getting $j Image"
   wget $k --output-document $z --show-progress
   wget $l --output-document $x --show-progress

   j=$(( j + 1 )) # increase number by 1
done
`

**Comment by univerone** [comment]
I solved this problem by typing
```
git lfs install
```
and then use git clone

**Comment by SaoussenMn** [comment]
Just wait for it , it happened to me either, because of your connection's speed

**Comment by MSC19950601** [comment]
> You can also download via wget. I wrote a small bash script for the purpose.
> 
> ```
> #!/bin/bash
> 
> img_url="https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/imaging.nii.gz"
> seg_url="https://media.githubusercontent.com/media/neheller/kits19/master/data/case_%05d/segmentation.nii.gz"
> 
> j=0
> while [ $j -le 210 ]
> do
>    # echo "$j"
>    k=`printf $img_url $j`
>    l=`printf $seg_url $j`
> 
>    z=`printf "imaging_%05d.nii.gz" $j`
>    x=`printf "segmentation_%05d.nii.gz" $j`
>    echo "Getting $j Image"
>    wget $k --output-document $z --show-progress
>    wget $l --output-document $x --show-progress
> 
>    j=$(( j + 1 )) # increase number by 1
> done
> ```

cannot run well on my linux.

**Comment by MountainAndMorning** [comment]
```python
import os
import requests
import SimpleITK as sitk
from tqdm import tqdm_notebook

dataDir = "/Users/<your user name>/Documents/kits19Data" # The target dir you want to store the downloaded files
caseNamePattern = "case_%05d"
dataUrl = "https://media.githubusercontent.com/media/neheller/kits19/master/data/"
imageUrlPattern = dataUrl + caseNamePattern + "/imaging.nii.gz"
segmentationUrlPattern = dataUrl + caseNamePattern + "/segmentation.nii.gz"

for case in tqdm_notebook(range(210)):
# Use tqdm_notebook in jupyter notebook to show the download progress
    caseDir = os.path.join(dataDir, caseNamePattern%case)
    os.mkdir(caseDir)
    
    imageUrl = imageUrlPattern%case
    imageR = requests.get(imageUrl)
    with open(os.path.join(caseDir, "imaging.nii.gz"), 'wb') as f:
        f.write(imageR.content)

    segmentationUrl = segmentationUrlPattern%case
    segmentationR = requests.get(segmentationUrl)
    with open(os.path.join(caseDir, "segmentation.nii.gz"), 'wb') as f:
        f.write(segmentationR.content)

```
