### ISSUE TITLE
Is spacing and direction of amended training data correct?

### ISSUE THREAD

**Issue by huyu398** [neheller/kits19#15]
3D Slicer shows wrong Image Spacing and Three Plane as following (Please watch inside the borders).
![wrong_image](https://user-images.githubusercontent.com/4333569/56186087-2c1d8a00-6059-11e9-8e27-a3252ca3e59d.png)

I fixed Image Spacing and Direction by SimpleITK.
```python
import SimpleITK as sitk
image = sitk.ReadImage('./data/case_00000/imaging.nii.gz')
image.SetDirection((0,0,1,0,1,0,-1,0,0))
image.SetSpacing((0.5, 0.919921875, 0.919921875)) # this values from data/kits.json
sitk.WriteImage(image, './data/case_00000/imaging_fix.nii.gz')
```
3D Slicer shows correct Image Spacing and Three Plane as following.
![correct_image](https://user-images.githubusercontent.com/4333569/56186565-bd413080-605a-11e9-9eeb-ac37edf4437c.png)

I checked only Case 00000 and 00001, but other cases should be wrong too.

Thank you.

**Comment by dericdesta** [comment]
Unfortunately, same issue here with ITK SNAP.
`case_00000`:
![kits19](https://user-images.githubusercontent.com/7849983/56209298-74d24480-6053-11e9-8704-026e157f3f8d.png)

**Comment by ghumpire** [comment]
Something similar was previously reported here #8

**Comment by neheller** [comment]
There is still an issue as of 236685c7fd70c74b29cc8732bd5b9e3903737627 but I'm pushing a fix (third time's the charm!). See my comment in #8 for more details.

**Comment by neheller** [comment]
Appears to be fixed now. As always, feel free to reopen if the issue continues.
