### ISSUE TITLE
code error !!!

### ISSUE THREAD

**Issue by turkfuat** [neheller/kits19#16]
usage: ipykernel_launcher.py [-h] -c CASE_ID -d DESTINATION
                             [-u UPPER_HU_BOUND] [-l LOWER_HU_BOUND]
ipykernel_launcher.py: error: the following arguments are required: -c/--case_id, -d/--destination

**Comment by neheller** [comment]
Make sure you're giving the required command line arguments (-c and -d).
```
python3 starter_code/visualize.py -c 123 -d <destination>
```

**Comment by turkfuat** [comment]
I'm a beginner. can you explain in a little more detail what I should do?

**Comment by neheller** [comment]
That depends on the environment you're running your code in. If you're running this from a terminal on linux, it should just be a matter of running the command above. If you're running from a python environment in the repository root, I'd recommend just calling the `visualize` function. For example:
```python3
>>> import starter_code.visualize
>>> starter_code.visualize.visualize(123, "/path/to/destination")
```

You can look at the source in starter code for an example of how to load and access the data with nibabel. If you're just trying to visualize the data, [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php) is also a nice option.

**Comment by turkfuat** [comment]
actually ı want to do kidney tumors segmentation. This is my college thesis homework. I follow your work. I ask you for help on this. thanks in advance

________________________________
Gönderen: Nick Heller <notifications@github.com>
Gönderildi: 17 Nisan 2019 Çarşamba 17:53
Kime: neheller/kits19
Bilgi: turkfuat; Author
Konu: Re: [neheller/kits19] code error !!! (#16)


That depends on the environment you're running your code in. If you're running this from a terminal on linux, it should just be a matter of running the command above. If you're running from a python environment in the repository root, I'd recommend just calling the visualize function. For example:

>>> import starter_code.visualize
>>> starter_code.visualize.visualize(123, "/path/to/destination")

You can look at the source in starter code for an example of how to load and access the data with nibabel. If you're just trying to visualize the data, ITK-SNAP<http://www.itksnap.org/pmwiki/pmwiki.php> is also a nice option.

**Comment by neheller** [comment]
Okay, well we can continue our discussion on this thread but I'm going to close the issue since this is not an error in the code itself. 

What's your operating system?

**Comment by turkfuat** [comment]
I finally got it.  Now my main question is: how can I not say this segmentation with other images?  Can you also apply deep learning?

iPhone’umdan gönderildi

Nick Heller <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (20 Nis 2019 17:58):


Okay, well we can continue our discussion on this thread but I'm going to close the issue since this is not an error in the code itself.

What's your operating system?

**Comment by turkfuat** [comment]
Hello sir
I am a PhD student at Kırıkkale University. I want to use 300 KITS19 dateset. But there are 210 of them. How can I download the remaining 90 datasets?
Thank you in advance.

**Comment by neheller** [comment]
The segmentation labels for cases 210 - 299 remain private so that people can continue to participate in the challenge in an "open call fashion" on [grand-challenge.org](https://kits19.grand-challenge.org)
