### ISSUE TITLE
Data Record,  KiTS.json file

### ISSUE THREAD

**Issue by sharmarochan** [neheller/kits19#17]
Only 3 fields are present in KiTS.json. But in the research paper more than 50 attributes are described.

for each case the json file has only:

 {
    "case_id": "case_00209",
    "captured_pixel_width": 0.78125,
    "captured_slice_thickness": 5
  }

**Comment by neheller** [comment]
As we mentioned in the preprint, we are still working on quality control and anonymization for the remaining attributes. Our intention was not for them to be used in the 2019 challenge, and thus you shouldn't count on their release prior to the challenge deadline.

**Comment by SmileJET** [comment]
Hi @neheller ,

Thanks for organizing this great challenge.

I wonder to know when we could have access to the attributes information mentioned in the preprint, such as birth year, nephrectomy year, gender and so on.

Best,
Jet

**Comment by neheller** [comment]
Sorry for the long delay. We are planning to release the clinical data within the next two weeks.
