### ISSUE TITLE
data load help

### ISSUE THREAD

**Issue by turkfuat** [neheller/kits19#18]
how to download data ? ı can't git lfs data

**Comment by turkfuat** [comment]
How can ı download

**Comment by JunMa11** [comment]
Could check whether you install git-lfs before cloning?

**Comment by ylink-lfs** [comment]
After installing git lfs, just use
`git clone https://github.com/neheller/kits19.git`
in your command prompt as cloning a common repository.

**Comment by turkfuat** [comment]
Thanks for your help. I managed to do what you said. my aim is to download these pictures into my computer, I think I can handle it when running the program.

________________________________
Gönderen: ylink <notifications@github.com>
Gönderildi: 26 Nisan 2019 Cuma 20:11
Kime: neheller/kits19
Bilgi: turkfuat; Author
Konu: Re: [neheller/kits19] data load help (#18)


After installing git lfs, just use
git clone https://github.com/neheller/kits19.git
in your command prompt as cloning a common repository.

**Comment by loaiibnka3b6** [comment]
i am reying to download the images dataset using "git clone https://github.com/neheller/kits19.git" 
however, the folders are empty? 
any suggestions plz?

**Comment by neheller** [comment]
They are totally empty, or just have small files? Have you ensured that git lfs is installed? Did any errors appear during clone?

**Comment by neheller** [comment]
The large image files have been moved to an external location which will hopefully be easier to access. I'd recommend cloning a fresh version of the repository and following the instructions on the README
