### ISSUE TITLE
 downloaded data's size only 1kb

### ISSUE THREAD

**Issue by dcxAccuRad** [neheller/kits19#19]
when use the comand `git clone https://github.com/neheller/kits19
Cloning into 'kits19'...
remote: Enumerating objects: 3876, done.
remote: Counting objects: 100% (3876/3876), done.
remote: Compressing objects: 100% (3843/3843), done.
remote: Total 3876 (delta 41), reused 3855 (delta 28), pack-reused 0
Receiving objects: 100% (3876/3876), 468.09 KiB | 70.00 KiB/s, done.
Resolving deltas: 100% (41/41), done.
Checking connectivity... done.
`

the imaging.nii.gz size only 1kb

**Comment by vatsal-sodha** [comment]
Make sure you clone after you start git-lfs 

`git lfs install`

**Comment by dcxAccuRad** [comment]
how to start git-lfs?

**Comment by dcxAccuRad** [comment]
> Make sure you clone after you start git-lfs
> 
> `git lfs install`

i have "pip install git-lfs"

**Comment by ghumpire** [comment]
This question was already answered on #7 and #14

**Comment by neheller** [comment]
Due to the previous discussion, I'm going to close this for now. Feel free to reopen if you don't find a solution in #5, #7, or #14.
