### ISSUE TITLE
breakpoint resume for data downloading

### ISSUE THREAD

**Issue by JunMa11** [neheller/kits19#20]
Hi @neheller 

When downloading the new data by 
> git clone -b interpolated --single-branch https://github.com/neheller/kits19

the network often breaks off, could you tell me how to resume the downloading from breakpoints?

Best,
Jun

**Comment by neheller** [comment]
You might find the discussion in #14 helpful

**Comment by JunMa11** [comment]
Got it. Thank you very much.
