### ISSUE TITLE
After 95% downloading showed the error "skipping object checkout, Git LFS is not installed.0 MB/s". Checked git lfs --version got the output. but unable to download the data. what i have to do

### ISSUE THREAD

**Issue by sivaskandha** [neheller/kits19#22]
Skipping object checkout, Git LFS is not installed.0 MB/s

**Comment by neheller** [comment]
#14 has some discussion that you might find helpful

**Comment by neheller** [comment]
The large image files have been moved to an external location which will hopefully be easier to access. I'd recommend cloning a fresh version of the repository and following the instructions on the README
