### ISSUE TITLE
Is the spacing of case 00088 really correct?

### ISSUE THREAD

**Issue by huyu398** [neheller/kits19#24]
This person has a waist of only about 15 cm.
This is too fine for adults, so I suspect that spacing may be wrong.
![Screenshot](https://user-images.githubusercontent.com/4333569/59334711-0ac5db00-8d36-11e9-861a-c1b9a8b06002.png)

**Comment by neheller** [comment]
The spacing is correct. This is actually a Wilms tumor on a patient less than one year old.

**Comment by huyu398** [comment]
Thanks for your replying!
