### ISSUE TITLE
 ImageFileError

### ISSUE THREAD

**Issue by divyanshuaggarwal** [neheller/kits19#25]
from starter_code.utils import load_case
​
volume, segmentation = load_case("case_00125")
​

throws the error : ImageFileError: Cannot work out file type of "/Users/divyanshuaggarwal/Desktop/kits19-master/data/case_00123/imaging.nii.gz"

**Comment by neheller** [comment]
This has been discussed in #5, #7, and #14. Feel free to reopen if you don't find what you need in one of those.
