### ISSUE TITLE
data download

### ISSUE THREAD

**Issue by jcwang123** [neheller/kits19#29]
how to fix this error and continue downloading
----------------------
Error downloading object: data/case_00008/imaging.nii.gz (ce45627): Smudge error: Error downloading data/case_00008/imaging.nii.gz (ce45627ceffdcd225655132ae50d9d1e7661d1c41f171e3419bb9ebd286e14d8): cannot write data to tempfile "/data/kits19/.git/lfs/incomplete/ce45627ceffdcd225655132ae50d9d1e7661d1c41f171e3419bb9ebd286e14d8.tmp": LFS: unexpected EOF

Errors logged to /data/kits19/.git/lfs/logs/20190704T230255.737132676.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/case_00008/imaging.nii.gz: smudge filter lfs failed

**Comment by neheller** [comment]
Maybe give this a try: https://github.com/git-lfs/git-lfs/issues/911#issuecomment-169998792

**Comment by neheller** [comment]
The large image files have been moved to an external location which will hopefully be easier to access. I'd recommend cloning a fresh version of the repository and following the instructions on the README
