### ISSUE TITLE
Test set submission instructions are unclear

### ISSUE THREAD

**Issue by FabianIsensee** [neheller/kits19#30]
Hi there,
I took this from Rules -> Submission format on the KiTS Homepage. Not sure if a github issue is the correct place of  asking this, so please feel free to redirect me.

> Predictions should be submitted as a zip (your-teamname.zip) archive of .nii.gz files named prediction_00210.nii.gz, ..., prediction_000299.npy corresponding to the ordered list of 90 test cases. That is, you should generate each of these prediction files in a particular directory, and then from that directory, run the following command:
> zip your-teamname.zip case_*.nii.gz

The name of the predicted segmentations is all over the place. First it's `prediction_XXXXX.nii.gz`, then the next one is `prediction_XXXXXX.npy` and finally in the last line it is `case_??.nii.gz`. Would be great if you could update this description.

Thank you so much for organizing this challenge and putting all the effort into this! It's a really nice dataset and also quite nicely annotated, despite the occasional hiccup people seem to have noticed regarding some of the cases! 

Best,
Fabian

**Comment by neheller** [comment]
Yikes, thanks for bringing this to my attention!

I will clean this up later today and then make a post in the forum. 

Thanks for the kind words about the challenge :)

**Comment by neheller** [comment]
I've updated the rules and the forum post can be found [here](https://discourse.kits-challenge.org/t/some-notes-on-evaluation/260). Thanks again for spotting this.

**Comment by FabianIsensee** [comment]
Thank you for fixing this so quickly :-)
Best,
Fabian
