### ISSUE TITLE
Extracting images from NIFTI

### ISSUE THREAD

**Issue by tetelias** [neheller/kits19#31]
Starter code works fine and some minor details were cleared by looking at nibabel docs, but now I have a numpy array of float64 with values in +/- thousands without a clear understanding of what to do next: do I cast it to uint8, do I normalize it to [0;1] or maybe it's int16 image. Could you please clarify?

**Comment by neheller** [comment]
The values you're seeing are called [Hounsfield Units](https://en.wikipedia.org/wiki/Hounsfield_scale), and they're captured at a higher level of precision than can be represented by 8-bit pixels in normal grayscale images.

If you want to visualize the images, one thing you can do is clip the values above and below at arbitrary thresholds and then normalize to 0-255 (at great loss of precision). This is what I do in the starter code. For input to a model, I leave it for you to decide how to best transform/normalize the data.
