### ISSUE TITLE
Will the  interpolated test data be released? 

### ISSUE THREAD

**Issue by luciaL** [neheller/kits19#34]

**Comment by JunMa11** [comment]
If you have already cloned the repository for the training data on branch `interpolated`, you can simply run `git pull origin interpolated`. If I understand Git LFS correctly, this will download the full test files for the `interpolated` branch and only small references to test files on the `master` branch.

_Originally posted by @neheller in https://github.com/neheller/kits19/issues/32#issuecomment-511615884_

**Comment by luciaL** [comment]
@
