### ISSUE TITLE
Python script to download Test Files (case_00210 to case_00299)

### ISSUE THREAD

**Issue by sharmarochan** [neheller/kits19#36]
import os
import requests
from tqdm import tqdm

dataDir = r"<your dir >" # The target dir you want to store the downloaded files
caseNamePattern = "case_%05d"
dataUrl = "https://media.githubusercontent.com/media/neheller/kits19/master/data/"
imageUrlPattern = dataUrl + caseNamePattern + "/imaging.nii.gz"

#segmentationUrlPattern = dataUrl + caseNamePattern + "/segmentation.nii.gz"

for case in tqdm(range(210, 300)): # Use tqdm_notebook in jupyter notebook to show the download progress
    caseDir = os.path.join(dataDir, caseNamePattern%case)
    print(caseDir)
    os.mkdir(caseDir)
    imageUrl = imageUrlPattern%case
    imageR = requests.get(imageUrl)
    with open(os.path.join(caseDir, "imaging.nii.gz"), 'wb') as f:
        f.write(imageR.content)

[kits data download script.txt](https://github.com/neheller/kits19/files/3426612/kits.data.download.script.txt)

**Comment by sharmarochan** [comment]
to download train files:



import os
import requests
from tqdm import tqdm
dataDir = r"<you dir>" # The target dir you want to store the downloaded files
caseNamePattern = "case_%05d"
dataUrl = "https://github.com/neheller/kits19/tree/master/data/"
imageUrlPattern = dataUrl + caseNamePattern + "/imaging.nii.gz"
segmentationUrlPattern = dataUrl + caseNamePattern + "/segmentation.nii.gz"
for case in tqdm(range(0, 210)):
# Use tqdm_notebook in jupyter notebook to show the download progress
    caseDir = os.path.join(dataDir, caseNamePattern%case)
    print(caseDir)
    os.mkdir(caseDir)
    imageUrl = imageUrlPattern%case
    imageR = requests.get(imageUrl)
    with open(os.path.join(caseDir, "imaging.nii.gz"), 'wb') as f:
        f.write(imageR.content)
    segmentationUrl = segmentationUrlPattern%case
    segmentationR = requests.get(segmentationUrl)
    with open(os.path.join(caseDir, "segmentation.nii.gz"), 'wb') as f:
        f.write(segmentationR.content)

**Comment by sharmarochan** [comment]
`import os
import requests
from tqdm import tqdm

dataDir = r"F:\kits19\data\test" # The target dir you want to store the downloaded files
caseNamePattern = "case_%05d"
dataUrl = "https://github.com/neheller/kits19/tree/master/data/"
imageUrlPattern = dataUrl + caseNamePattern + "/imaging.nii.gz"

segmentationUrlPattern = dataUrl + caseNamePattern + "/segmentation.nii.gz"

for case in tqdm(range(0, 210)):
# Use tqdm_notebook in jupyter notebook to show the download progress
    caseDir = os.path.join(dataDir, caseNamePattern%case)
    print(caseDir)
    os.mkdir(caseDir)
    
    imageUrl = imageUrlPattern%case
    imageR = requests.get(imageUrl)
    with open(os.path.join(caseDir, "imaging.nii.gz"), 'wb') as f:
        f.write(imageR.content)

    segmentationUrl = segmentationUrlPattern%case
    segmentationR = requests.get(segmentationUrl)
    with open(os.path.join(caseDir, "segmentation.nii.gz"), 'wb') as f:
        f.write(segmentationR.content)
        `

**Comment by neheller** [comment]
Thanks for providing this, but the access has now changed and this will no longer work. In the foreseeable future, most people will be downloading the whole dataset at once so hopefully something like this won't be needed.

**Comment by sharmarochan** [comment]
Hi neheller,
Thanks for the update. At that time, I was not able to download the test data set using lfs. So working under the submission deadline, I made this script to download test dataset. I shared it here so that others can get some help. I am sure people will update this code to working stage by doing some alterations.
Regards
ROCHAN
