### ISSUE TITLE
Statistical comparisons for top solutions

### ISSUE THREAD

**Issue by JunMa11** [neheller/kits19#37]
Dear @neheller,

For the ranking scheme,
> Teams will be ranked by their average score per case, with the highest being the winner.

Would it be possible to add **pairwise statistical comparisons** between top solutions as [BraTS](https://arxiv.org/pdf/1811.02629.pdf), [Decathlon](http://medicaldecathlon.com/files/MSD-Ranking-scheme.pdf) and [iSeg](http://iseg2017.web.unc.edu/files/2019/02/Benchmark-on-Automatic-6-month-old-Infant-Brain-Segmentation-Algorithms.pdf) did?

This may help to identify the real best solution because a small performance improvement can't indicate particular dominance of a method over the others. 

Thanks for organizing the great challenge, and I really enjoy it.
Looking forward to your reply!

Best,
Jun

**Comment by neheller** [comment]
Hi @JunMa11,

Yes, we're going to use the bootstrap for this. We'll describe the method in some detail when we release the leaderboard, but we plan to follow what's described in this paper: https://arxiv.org/abs/1806.02051

Cheers,
Nick

**Comment by JunMa11** [comment]
Hi @neheller ,

Thank you very much for the quick reply.
I'm so happy that you have considered this. KiTS is really one of the best organized challenges. Again, thank you and all other organizers.

Best,
Jun
