### ISSUE TITLE
No module named starter_code

### ISSUE THREAD

**Issue by ucalyptus** [neheller/kits19#4]
sayantan@kali:~/kits19$ python3 starter_code/visualize.py -c case 123 -d /home/sayantan/Desktop/
Traceback (most recent call last):
  File "starter_code/visualize.py", line 7, in <module>
    from starter_code.utils import load_case
ModuleNotFoundError: No module named 'starter_code'

**Comment by neheller** [comment]
First of all, the command line args won't be recognized. Try
```bash
python3 starter_code/visualize.py -c case_00123 -d /home/sayantan/Desktop/
```
But that should give you a different error than "Module Not Found". So far I'm having trouble reproducing, what's your python version?

**Comment by ucalyptus** [comment]
3.6.8

**Comment by neheller** [comment]
Interesting. Python 3.6.8 isn't giving me any trouble on Ubuntu 18.04. What does it tell you when you try the following?
```bash
python3 -m starter_code.visualize -c case_00123 -d /home/sayantan/Desktop/
```

**Comment by sharmarochan** [comment]
its working fine in python3.7
