### ISSUE TITLE
Full Installation Guide

### ISSUE THREAD

**Issue by jchen42703** [neheller/kits19#45]
I think it's worth mentioning that when cloning the repository directory with `git clone https://github.com/neheller/kits19`, the segmentations are not always cloned.

I ended having to run 
```
git lfs install --skip-smudge --skip-repo <- also added this
git clone https://github.com/neheller/kits19
cd kits19
git lfs pull <- added this
```
to get the segmentations to install fully.

Just thought it's something worth noting on the README. Wonder if this was true for other people as well?

**Comment by neheller** [comment]
When is the last time you tried this? The repository should be free of LFS now.

**Comment by jchen42703** [comment]
Right now (in Colab). I had a problem with git rev-parse when I tried the README method. I thought to try git lfs again after seeing that the segmentation files are still being stored by git lfs:
![](https://i.imgur.com/5CxV7i5.png)

**Comment by neheller** [comment]
Shoot, not sure how I missed this when testing. I'll dig into it now

**Comment by neheller** [comment]
How about now?
