### ISSUE TITLE
Lack of knowledge in kits.json file

### ISSUE THREAD

**Issue by ahmetkrgztr** [neheller/kits19#47]
In the 'The Cancer Imaging Archive (TCIA): Maintaining and Operating a Public Information Repository' paper N. Heller et al. said that there is information about a lot of things but we have the only pixel width and slice thickness. We don't have  'pathology t stage' – 'pathology n stage' and  'pathology m stage' etc. Can you please share others too?
Thanks

**Comment by neheller** [comment]
Sorry for the delay on this. This data has been included in the most recent commit.

Best,
Nick
