### ISSUE TITLE
Cannot work out file type of "nii.gz"

### ISSUE THREAD

**Issue by sharmarochan** [neheller/kits19#5]
ImageFileError: Cannot work out file type of "C:\Users\tensor19\Desktop\kits19\data\case_00009\imaging.nii.gz"

**Comment by sharmarochan** [comment]
clone it using git clone from cmd

**Comment by neheller** [comment]
Usually this happens when `git clone` was run before installing [git-lfs](https://git-lfs.github.com/). Please ensure that git-lfs is installed and then retry the clone. 

Note that simply running `git pull` after installing git-lfs will not work.

**Comment by ucalyptus** [comment]
Have the same issue, hopefully @neheller 's suggestion works for my problem as well

**Comment by neheller** [comment]
Any update on this?

**Comment by sharmarochan** [comment]
use git pull from cmd only.

**Comment by neheller** [comment]
Okay, so that worked? Can I close the issue?

**Comment by sharmarochan** [comment]
Yes
