### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by tiaoguoyunduan** [neheller/kits19#51]
when I was running "python -m starter_code.get_imaging" to get the data
it lead to an ERROR
"PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'D:\\kits19-master\\starter_code\\temp.tmp' -> 'data\\case_00000\\imaging.nii.gz'"
but I have run nothing but this

can I have another way to get these data?such as github?

**Comment by kirangpcet** [comment]
Yes I too had same error when I was running "python -m starter_code.get_imaging" to get the data
it lead to an ERROR
"PermissionError:

**Comment by tiaoguoyunduan** [comment]
> 是的，我在运行“ python -m starter_code.get_imaging”以获取
> 导致错误
> “ PermissionError：

I'm sorry that I haven't found the solution and can't help you

**Comment by neheller** [comment]
The download script first stores the image in a temporary file in the root of the repository, then when the download finishes, it copies that file to its appropriate spot in the `data/` folder. Is it possible you don't have write permissions in the destination directory?

**Comment by tiaoguoyunduan** [comment]
> The download script first stores the image in a temporary file in the root of the repository, then when the download finishes, it copies that file to its appropriate spot in the `data/` folder. Is it possible you don't have write permissions in the destination directory?

no, the error is the other process is using the file temp.tmp, but I have run nothing but this python process，and I have tried to run this by administrator. whatever, thank you for answering!!

**Comment by neheller** [comment]
I think I may have fixed the problem. Windows apparently won't let you `move()` files when you're within a `with` clause. Please pull origin and give it another try.

**Comment by tiaoguoyunduan** [comment]
> I think I may have fixed the problem. Windows apparently won't let you `move()` files when you're within a `with open()` clause. Please pull origin and give it another try.

you mean that I need to adjust the python program to the right way that can run in windows?Or just change another directory and try again? When I run this program in CMD, I haven't open the file or directory.
I am sorry that I haven't understood the problem,  could you please explain it more specifically? I am just starting to study machine learning.

**Comment by neheller** [comment]
No worries! I've updated the script such that I think it will work now. In when you're in the `kits19` directory, run `git pull` and then try `python3 -m starter_code.get_imaging` again

**Comment by tiaoguoyunduan** [comment]
> No worries! I've updated the script such that I think it will work now. In when you're in the `kits19` directory, run `git pull` and then try `python3 -m starter_code.get_imaging` again

cool!! It's late for me now, I am in Asia I will try again tomorrow.Thank you so much!!

**Comment by tiaoguoyunduan** [comment]
Great! The problem is fixed!
