### ISSUE TITLE
I keep getting this while using git bash 

### ISSUE THREAD

**Issue by Ganew018** [neheller/kits19#54]
! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/Ganew018/Ganew.git'
hint: Updates were rejected because the remote contains work that you do
not have locally. This is usually caused by another repository pushing
to the same ref. You may want to first integrate the remote changes (e.g., 'git pull ...') before pushing again.
See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by neheller** [comment]
Always make sure to pull before pushing. It will probably prompt you to provide a message about why the merge was necessary when you pull.
```
git pull
git push
```
