### ISSUE TITLE
how many images are there, what resolution, size, pixel depth (8 or 16 bits)? I need to Know please.

### ISSUE THREAD

**Issue by orellanabrain** [neheller/kits19#55]

**Comment by orellanabrain** [comment]
I want to apply the watersheds transform to detect Renal Carcinomas cell, but i need to know how many images are there, what resolution, size, pixel depth (8 or 16 bits)?

**Comment by neheller** [comment]
There are 300 images, and 210 have public segmentations available. The resolution is quite variable, you can find info about it in the [challenge's journal article](https://arxiv.org/pdf/1912.01054.pdf). Figure 3 in particular is probably what you're after. I believe the depth is 16 bits in all images, but I might be mistaken.
