### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by Chrobot129** [neheller/kits19#57]
Cases do not have imaging.nii.giz files

**Comment by neheller** [comment]
From bash, you can use the following commands to get the full dataset
```
git clone https://github.com/neheller/kits19
cd kits19
pip3 install -r requirements.txt
python3 -m starter_code.get_imaging
```
The imaging files had to be moved because of their size, but the `get_imaging.py` script will bring them down into their correct spots. There's more info about this in the README.
