### ISSUE TITLE
kits.json file has no information about voxel spacing

### ISSUE THREAD

**Issue by PennyCoder5704** [neheller/kits19#59]
Dear neheller,

I went through the Json file, but kits.json file has no information about voxel spacing.

Best regards,
Penny, Zhang

**Comment by neheller** [comment]
I suppose you're right! My apologies on this. It may take up to a week to fix since I'm currently out of the office.

**Comment by cameliaburlacu98** [comment]
Now, the kits.json file has no information about voxel spacing. Can you give the json file with information about voxel spacing? Thank you so much!

**Comment by neheller** [comment]
Sorry for the long delay. Solved by #66
