### ISSUE TITLE
Some cases have common error

### ISSUE THREAD

**Issue by shawnyuen** [neheller/kits19#6]
Thanks for sharing the large-scale dataset.

I open these nii.gz files via ITK-SNAP, and found the following cases having common error: **case_00015**, **case_00025**, **case_00061** and **case_00117**, repeating some slices containing kidney and tumor, but without corresponding mask 'kidney' and mask 'tumor'.

I recommend you remove these slices in the above three cases.

**Comment by neheller** [comment]
Thanks for helping with quality assurance! We'll look into what's going on here and update the data when we find a fix.

**Comment by luvWY** [comment]
> Thanks for sharing the large-scale dataset.
> 
> I open these nii.gz files via ITK-SNAP, and found the following cases having common error: **case_00015**, **case_00025**, **case_00061** and **case_00117**, repeating some slices containing kidney and tumor, but without corresponding mask 'kidney' and mask 'tumor'.
> 
> I recommend you remove these slices in the above three cases.

I download the dataset 5five days ago and I use np.max to check 'case_00025' segmentation label ... however there is 2 or 1 pixel... How to conclude " without corresponding mask 'kidney' and mask 'tumor'." I just wanna know whether I miss something..

**Comment by neheller** [comment]
In `case_00025` for instance, somehow the imaging taken at a different contrast phase got appended to the end of the phase that we annotated. So there are annotated kidneys and tumor followed by unannotated kidneys and tumor.

**Comment by luvWY** [comment]
> In `case_00025` for instance, somehow the imaging taken at a different contrast phase got appended to the end of the phase that we annotated. So there are annotated kidneys and tumor followed by unannotated kidneys and tumor.

OK..I check the code. You are right. I also found "case_00160" has a different shape of img: (512, 796) while others are (512, 512).. I dont know whether it's ok. I just post it here..

**Comment by neheller** [comment]
It is somewhat odd that case_00160 has a different shape, but it's not an error. When building your model, you should account for the fact that the test cases might not all be 512x512.

**Comment by neheller** [comment]
Case 15 was replaced entirely for unrelated reasons, and the other three have been cropped accordingly. Thanks again for pointing this out.
