### ISSUE TITLE
data 

### ISSUE THREAD

**Issue by ines1985** [neheller/kits19#60]
good afternoon,
I have downoaled the data but I found only the segmentation.nii data in the data file.
I want to get the imaging data.
sincerly

**Comment by neheller** [comment]
It sounds like you've already done the first line below, but please make sure to run all of the following commands in order to download the full dataset (from `README.md`).
```
git clone https://github.com/neheller/kits19
cd kits19
pip3 install -r requirements.txt
python3 -m starter_code.get_imaging
```

**Comment by WillX1998** [comment]
What program did you use to download the full dataset?
