### ISSUE TITLE
Trouble obtaining data

### ISSUE THREAD

**Issue by WillX1998** [neheller/kits19#62]
Hi,

Does anyone know how to access the actual image data, not the segmentation images, without using Python? I'm trying to do my own segmentation using MATLAB.

Thank you.

**Comment by WillX1998** [comment]
Hi,

Thank you for responding. I've never used Bash before. Is that the only way to download the imaging data?

**Comment by WillX1998** [comment]
Can you please walk me through using Git Bash to download the images? I tried running the code and it said the images were not found.

**Comment by neheller** [comment]
I'm not sure why the images wouldn't be found since it works on my end. There must be some other problem when using the above with Git Bash. How about the following MATLAB script?
```matlab
if ~exist('data', 'dir')
    mkdir('data');
end
for i = 0:299
    case_dir = fullfile('data', sprintf('case_%05d', i));
    if ~exist(case_dir, 'dir')
        mkdir(case_dir);
    end
    websave(fullfile(case_dir, 'imaging.nii.gz'), sprintf('https://kits19.sfo2.digitaloceanspaces.com/master_%05d.nii.gz', i), 'timeout',20);
end
```

**Comment by WillX1998** [comment]
Hi I managed to get the images. Thank you!
