### ISSUE TITLE
Problem about downloading data

### ISSUE THREAD

**Issue by liuquande** [neheller/kits19#7]
I've installed git lfs successfully and it seems that I could also clone the git repo successfully.
While the size of each .nii file I download is only "134 bytes".
Could anyone help me.
Thanks!

Here's the output:
~/Desktop/Research/Github/kits19$ git clone https://github.com/neheller/kits19
Cloning into 'kits19'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
Checking out files: 100% (429/429), done.

**Comment by neheller** [comment]
This is very interesting. When I run the clone, I get:
```bash
$ git clone https://github.com/neheller/kits19
Cloning into 'kits19'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 3.10 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Filtering content: 100% (420/420), 18.91 GiB | 88.21 MiB/s, done.
```
Whereas if I clone without Git LFS installed, it gives me this:
```bash
$ git clone https://github.com/neheller/kits19
Cloning into 'kits19'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
```
It's not clear to me where the 429 is coming from. Did the clone take a long time for you, or is it quick like a normal repo? What happens when you run `git checkout data`?

**Comment by liuquande** [comment]
The downloading process is very quick just within several seconds.
Actually I have installed Git LFS and tried with "git lfs --version" which gives me like this:
~$ git lfs --version
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)

**Comment by liuquande** [comment]
> This is very interesting. When I run the clone, I get:
> 
> ```shell
> $ git clone https://github.com/neheller/kits19
> Cloning into 'kits19'...
> remote: Enumerating objects: 676, done.
> remote: Counting objects: 100% (676/676), done.
> remote: Compressing objects: 100% (671/671), done.
> remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
> Receiving objects: 100% (676/676), 92.89 KiB | 3.10 MiB/s, done.
> Resolving deltas: 100% (17/17), done.
> Filtering content: 100% (420/420), 18.91 GiB | 88.21 MiB/s, done.
> ```
> 
> Whereas if I clone without Git LFS installed, it gives me this:
> 
> ```shell
> $ git clone https://github.com/neheller/kits19
> Cloning into 'kits19'...
> remote: Enumerating objects: 676, done.
> remote: Counting objects: 100% (676/676), done.
> remote: Compressing objects: 100% (671/671), done.
> remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
> Receiving objects: 100% (676/676), 92.89 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (17/17), done.
> Checking connectivity... done.
> ```
> 
> It's not clear to me where the 429 is coming from. Did the clone take a long time for you, or is it quick like a normal repo? What happens when you run `git checkout data`?

Thanks for your reply.
The downloading process is very quick just within several seconds.
Actually I have installed Git LFS and tried with "git lfs --version" which gives me like this:
~$ git lfs --version
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)

**Comment by liuquande** [comment]
@neheller 
Thanks for your reply.
The downloading process is very quick just within several seconds.
Actually I have installed Git LFS and tried with "git lfs --version" which gives me like this:
~$ git lfs --version
git-lfs/2.7.1 (GitHub; linux amd64; go 1.12; git 6b7fb6e3)

**Comment by liuquande** [comment]
When I clone without Git LFS installed, it gives me the same as you:
`Cloning into 'kits19'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.`

While when download with lfs installed successfully, it report this:
`Cloning into 'kits19'...
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 62.00 KiB/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
Downloading data/case_00000/imaging.nii.gz (226 MB)
Error downloading object: data/case_00000/imaging.nii.gz (540dab5): Smudge error: Error downloading data/case_00000/imaging.nii.gz (540dab5fb8d6b025f161d1d88632a9a45f1f2f974691588900bc95e9c7a3289d): batch response: Post https://github.com/neheller/kits19.git/info/lfs/objects/batch: proxyconnect tcp: tls: first record does not look like a TLS handshake

Errors logged to /home/eric/Desktop/Research/Github/kits19/.git/lfs/logs/20190320T214002.948991924.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/case_00000/imaging.nii.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

Could anyone help me?

Thanks!!!!

**Comment by liuquande** [comment]
When I clone without Git LFS installed, it gives me the same as you:
`Cloning into 'kits19'... remote: Enumerating objects: 676, done. remote: Counting objects: 100% (676/676), done. remote: Compressing objects: 100% (671/671), done. remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0 Receiving objects: 100% (676/676), 92.89 KiB | 0 bytes/s, done. Resolving deltas: 100% (17/17), done. Checking connectivity... done.`

While when download with lfs installed successfully, it report this:
```
remote: Enumerating objects: 676, done.
remote: Counting objects: 100% (676/676), done.
remote: Compressing objects: 100% (671/671), done.
remote: Total 676 (delta 17), reused 638 (delta 0), pack-reused 0
Receiving objects: 100% (676/676), 92.89 KiB | 62.00 KiB/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
Downloading data/case_00000/imaging.nii.gz (226 MB)
Error downloading object: data/case_00000/imaging.nii.gz (540dab5): Smudge error: Error downloading data/case_00000/imaging.nii.gz (540dab5fb8d6b025f161d1d88632a9a45f1f2f974691588900bc95e9c7a3289d): batch response: Post https://github.com/neheller/kits19.git/info/lfs/objects/batch: proxyconnect tcp: tls: first record does not look like a TLS handshake

Errors logged to /home/eric/Desktop/Research/Github/kits19/.git/lfs/logs/20190320T214002.948991924.log
Use git lfs logs last to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: data/case_00000/imaging.nii.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

Could anyone help me?

Thanks!!!!

**Comment by michmichm** [comment]
I got same error when I installed git lfs to /home/me/bin and solved it when I installed git lfs directly to /home/me. Did you change git lfs's installer script?

**Comment by liuquande** [comment]
@michmichm thanks.
I have downloaded it using other computer.

**Comment by vatsal-sodha** [comment]
I encountered the same problem and what worked for me is to initialize git-lfs even after you install git-lfs you need to initialize it using below command
`git lfs install 
Git LFS initialized.`
then clone the repository.
