### ISSUE TITLE
Data segmentation File missing

### ISSUE THREAD

**Issue by kunaljangid01** [neheller/kits19#77]
Hi,
I need segmentation files for cases 210 to case 299 of KiTS23  as it is unavailable there. Can you please give me the data I need in my work?

Thankful.

**Comment by neheller** [comment]
Those are test set cases for the 2019 iteration of the challenge, so their labels are not publicly available. For labels for these files, please see the [neheller/kits23](https://github.com/neheller/kits23) repository
